name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    # We need to use an old runner for Xcode 11.7
    # TODO: Use a matrix instead
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: orion
    - name: Set Up Dependencies
      id: setup
      run: |
        brew install ldid make fakeroot
        echo "THEOS=${GITHUB_WORKSPACE}/theos" >> "${GITHUB_ENV}"
        echo "PATH=/usr/local/opt/make/libexec/gnubin:${PATH}" >> "${GITHUB_ENV}"
        echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
    - name: Install Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        ref: 153c50c49dbbac0b47b87f9480d8d2c5d6d2ace1
        path: theos
        submodules: recursive
    - name: Build Release
      run: |
        cd orion
        # Orion doesnt build with 12.5 atm due to a compiler bug (SR-14535)
        DEVELOPER_DIR=/Applications/Xcode_12.4.app/Contents/Developer make clean package FINALPACKAGE=1
        DEVELOPER_DIR=/Applications/Xcode_12.4.app/Contents/Developer make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        DEVELOPER_DIR=/Applications/Xcode_11.7.app/Contents/Developer make clean package FINALPACKAGE=1
        cd packages
        zip -yr9 Orion_${{ steps.setup.outputs.version }}.zip *
        cd ..
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.setup.outputs.version }}
        body: ''
        draft: true
        prerelease: false
    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/orion/packages/Orion_${{ steps.setup.outputs.version }}.zip
        asset_name: Orion_${{ steps.setup.outputs.version }}.zip
        asset_content_type: application/zip
